### ISSUE TITLE
Flashing red inaccessible chunks around loading areas and no minimap

### ISSUE THREAD

**Issue by Orangenal-name** [senseiwells/ChunkDebug#16] opened 2024-11-30 17:19 UTC
**Describe the bug**
I was using Dark's 1D mining cannon, which utilises some lazy loading TNT shenanigans, and as such I was using ChunkDebug to see when it was done, when I noticed that, not only was the minimap not working, but also that around the areas being loaded it was flashing red, which did not happen in older versions of the mod (I only recently updated)

**General Info**
Mod Version: Latest (2.1.2)
Minecraft Version: 1.21.1
List of other mods: YACL and Fabric Language Kotlin

**To Reproduce**
Use the 1D cannon from [this video](https://www.youtube.com/watch?v=5hq4TwvVp6o) (link in the description) by flicking the bottom lever, putting two items in the dispenser, flicking the top lever, and setting the gamerule specatorsGenerateChunks to false. Once the TNT stops after 5 minutes (you may want to use /tick rate x to get this to happen faster, you may see the chunks being loaded with red stuff around them)

**Expected behavior**
The minimap should stay when exiting the menu, and the chunks should not have the red stuff around them

**Crash Report / Latest Log**
[latest.log](https://github.com/user-attachments/files/17966212/latest.log)

**Screenshots / Videos**
https://github.com/user-attachments/assets/fd987df0-dc48-4b01-bc88-4a29a44e607a

**Additional info**
Add any other info about the problem here.
While testing whether this still happened without using other mods, I got kicked after pressing F6 to open the chunk debug menu directly

**Comment by senseiwells** [comment] 2024-11-30 17:38
To address both issues:
- The red flashing is a **feature**, if a chunk can be scheduled for unloading - if too many chunks are trying to be unloaded at once. Chunks turn red if they are *scheduled* for unloading but haven't quite unloaded yet.
- You seem to have omitted the fact that you are using feather client, which is known to cause many incompatibilities and is almost certainly the cause for ChunkDebug not rendering. I will not be fixing this issue for 1.21.1.
  - This issue may be 'accidentally' resolved in 1.21.4 due to some rendering changes I am making.

**Closed as completed by senseiwells** 2024-11-30 17:38 UTC
